/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package f1;

import javafx.application.Application;

public class App {
	public static void main(String[] args) {
		Application.launch(MainMenu.class, args);
	}
}
